import {
  checkA11yAria,
  checkA11yButtons,
  checkA11yDocumentTitle,
  checkA11yEmptyAlt,
  checkA11yEmptyLinks,
  checkA11yFieldNameId,
  checkA11yHeadings,
  checkA11yInputs,
  checkA11yLang,
  checkA11yMissingAlt,
  checkA11yTabIndex,
} from '@/checks/accessibility';
import {
  checkEmptyHeadings,
  checkHeadingOutline,
  checkLongHeadings,
  checkParagraphs,
  checkPlaceholders,
  checkRepeatedHeadings,
  checkWordCount,
} from '@/checks/content';
import {
  checkFormActionMethod,
  checkFormButtonType,
  checkFormCount,
  checkFormLabels,
  checkFormNames,
  checkFormPasswords,
  checkFormPlaceholders,
  checkFormRequired,
  checkFormSubmit,
} from '@/checks/forms';
import {
  checkImagesBroken,
  checkImagesDimensions,
  checkImagesEmptyAlt,
  checkImagesLazy,
  checkImagesMissingAlt,
  checkImagesOversized,
} from '@/checks/images';
import { checkEmptyHref, checkJavascriptLinks, checkLinkInventory, checkTargetBlank } from '@/checks/links';
import type { CheckFn } from '@/checks/runChecks';
import {
  checkCanonical,
  checkEmptyLinkText,
  checkH1Exists,
  checkHeadingHierarchy,
  checkHttps,
  checkInternalExternalLinks,
  checkMetaDescriptionExists,
  checkMetaDescriptionLength,
  checkMissingAlt,
  checkMultipleH1,
  checkOgDescription,
  checkOgImage,
  checkOgTitle,
  checkPageUrl,
  checkRobotsMeta,
  checkTitleExists,
  checkTitleLength,
  checkTwitterCard,
} from '@/checks/seo';
import {
  checkAssets,
  checkCharset,
  checkDomSize,
  checkFavicon,
  checkHtmlLangTechnical,
  checkTechnicalIdentity,
  checkTimings,
  checkViewport,
} from '@/checks/technical';

export const checkRegistry: CheckFn[] = [
  checkTitleExists,
  checkTitleLength,
  checkMetaDescriptionExists,
  checkMetaDescriptionLength,
  checkCanonical,
  checkRobotsMeta,
  checkOgTitle,
  checkOgDescription,
  checkOgImage,
  checkTwitterCard,
  checkH1Exists,
  checkMultipleH1,
  checkHeadingHierarchy,
  checkMissingAlt,
  checkEmptyLinkText,
  checkInternalExternalLinks,
  checkPageUrl,
  checkHttps,
  checkA11yMissingAlt,
  checkA11yButtons,
  checkA11yInputs,
  checkA11yEmptyLinks,
  checkA11yLang,
  checkA11yHeadings,
  checkA11yTabIndex,
  checkA11yAria,
  checkA11yFieldNameId,
  checkA11yEmptyAlt,
  checkA11yDocumentTitle,
  checkImagesMissingAlt,
  checkImagesEmptyAlt,
  checkImagesDimensions,
  checkImagesLazy,
  checkImagesOversized,
  checkImagesBroken,
  checkLinkInventory,
  checkEmptyHref,
  checkJavascriptLinks,
  checkTargetBlank,
  checkFormCount,
  checkFormLabels,
  checkFormPlaceholders,
  checkFormNames,
  checkFormPasswords,
  checkFormRequired,
  checkFormButtonType,
  checkFormSubmit,
  checkFormActionMethod,
  checkWordCount,
  checkParagraphs,
  checkHeadingOutline,
  checkEmptyHeadings,
  checkLongHeadings,
  checkRepeatedHeadings,
  checkPlaceholders,
  checkTechnicalIdentity,
  checkCharset,
  checkHtmlLangTechnical,
  checkViewport,
  checkFavicon,
  checkAssets,
  checkDomSize,
  checkTimings,
];
